### PR TITLE
Change Identifier To String #128

### LINKED ISSUE #128: When submitting a DOI, if the identifier is an integer the submission fails
## 🐛 Describe the bug

See screenshot:

Screen Shot 2022-03-31 at 4 50 48 PM

The error when clicking on submit is:
```
Submission Error: InputFormatException
Description: Unable to parse DOI objects from provided json file "/var/folders/nx/k6m8glmn385d9tp9dj_6whxh0000gq/T/labels_9wqogkve.json" Reason: JSON record at index 0 does not conform to the DataCite Schema, reason(s): identifiers/0/identifier: {'_text': 20151} is not of type 'string'
Please address the error then try again.

```

The json send to the API is wrong:
`{"data":{"id":"10.17189/20151","type":"dois","attributes":{"doi":"10.17189/20151","suffix":{"_text":20151},"identifiers":[{"identifier":{"_text":20151},"identifierType":"IAD ID"},{"identifier":"urn:nasa:pds:insight_cameras::1.0","identifierType":"Site ID"}],"creators":[{"nameType":"Personal","name":"J. Maki"},{"nameType":"Personal","name":"P. Zamani"},{"nameType":"Personal","name":"H. Abarca"},{"nameType":"Personal","name":"R. Deen"}],"titles":[{"title":"InSight Cameras Bundle","lang":"en"}],"publisher":"NASA Planetary Data System","publicationYear":"2019","contributors":[{"nameType":"Organizational","name":"Planetary Data System: PDS Cartography and Imaging Sciences Discipline Node","contributorType":"DataCurator"}],"types":{"resourceTypeGeneral":"Collection","resourceType":"PDS4 Bundle"},"url":"https://pds.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Ainsight_cameras&version=1.0","created":"2020-05-07T22:12:05.000000Z","updated":"2020-05-07T22:12:05.000000Z","state":"findable","language":"en","schemaVersion":"http://datacite.org/schema/kernel-4","subjects":[{"subject":"Wavelet analysis"}]}}}
`

Where it says:
"suffix":{"_text":20151} it should be "suffix": "20151" or 20151

and

"identifier":{"_text":20151} it should be "identifier": "20151"

## 📜 To Reproduce
1. Submit for review a DOI which identifier is an integer

## 🕵️ Expected behavior

The DOI should be accepted for review.

## 🖥 System Info

---

### PR DESCRIPTION
**Pull request by eddiesarevalo**
## 🗒️ Summary
-Added a fix for changing the identifier to a string. The parser converts it to _text but should just be a normal string. This only happens when the identifier is a number. If it is a string it doesn't get converted that way.

## ⚙️ Test Data and/or Report
Run the doi-ui locally and connect to the api through a tunnel.
Create a dummy doi in create menu. Copy the doi number and open the release page. Change the value of the identifier to a number for example `1234` Then submit. There should be no error about `{"_text":20151}` The number will be what was inputted before.

The upload payload in the console should look like: `identifiers: [{identifier: "1234", identifierType: "Site ID"}]` for the identifiers part. The number will be what was inputted before.

The error before was 
`identifiers: [{identifier: {"_text":20151}, identifierType: "Site ID"}]`

## ♻️ Related Issues
-fixes #128

### CODE REVIEW

File: src/sagas/index.js [hunk 1]
```diff
@@ -53,6 +53,15 @@ const changeRecordSinglesToArrays = function(record) {
             if(record.data.attributes.prefix){
                 record.data.attributes.prefix = String(record.data.attributes.prefix._text);
             }
+            if(record.data.attributes.identifiers){
+                if(record.data.attributes.identifiers[0]){
```
Comment (tloubrieu-jpl) [inline src/sagas/index.js:57]: Hi @eddiesarevalo There is a list of identifiers so that might not happen on the first one.

I am also worrying about the fact that that might happen somewhere else in the XML. Would there be a solution on parameterizing the conversion so that we never have there _text attributes ?

Thanks

**Review by tloubrieu-jpl — CHANGES_REQUESTED** [review]
Thanks @eddiesarevalo. I don't think the solution is robust enough for other cases that we might have. See my comment in the review. I might be wrong about that...
We can discuss that at the breakout today. That would be good if you can have a more generic solution for that.
Thanks

File: src/sagas/index.js (hunk 1 above)
Comment (eddiesarevalo) [reply src/sagas/index.js:57]: Hello @tloubrieu-jpl You are right about the list. This will only do the first one. I need to set it to do a list.

The main problem I faced when dealing with the conversion between xml and json was coming up with a way to remove the _text attributes and set the arrays for values.

I'm using this library: https://www.npmjs.com/package/xml-js

It converts xml to json and back, however there are some limitations to what any converter can do. The issues I faced here were first, that the converter does not know the types of what a json object should be from just the xml. It only sees text. 

For example the xml tag `<publicationYear>2020</publicationYear>` is it text or number? The converter will just detect it as a string and put it as `{_text:'2020'}`

Second the converter doesn't know if an item in xml is an array or single item.

Here is the example of the problem. Given the tag `creators`
```html
<creators>
     <nameType>Personal</nameType>
     <name>Arevalo Eddie</name>
</creators>
```

The converter doesn't know this is not a single object:
```javascript
creators:{
          nameType:'Personal'
          name:'Eddie'
}
```

and should instead be an array:
```javascript
creators:[{
          nameType:'Personal'
          name:'Eddie'
}]
```

I created that section of code above to do the conversions that the converter would not be able to do. First to remove the _text if it exists and second to convert to arrays the objects that should be an array.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I added the fix for an array of identifiers.

**Comment by tloubrieu-jpl** [comment]
Thanks Eddie for the fix for multiple identifier.

I've tested the update but I am bumping into the same type of error for the tag suffix, just above.

See this example DOI XML (I should have started there):
`<data>
  <id>10.17189/20151</id>
  <type>dois</type>
  <attributes>
    <doi>10.17189/20151</doi>
    <suffix>20151</suffix>
    <identifiers>
      <identifier>20151</identifier>
      <identifierType>IAD ID</identifierType>
    </identifiers>
    <identifiers>
      <identifier>urn:nasa:pds:insight_cameras::1.0</identifier>
      <identifierType>Site ID</identifierType>
    </identifiers>
    <creators>
      <nameType>Personal</nameType>
      <name>J. Maki</name>
    </creators>
    <creators>
      <nameType>Personal</nameType>
      <name>P. Zamani</name>
    </creators>
    <creators>
      <nameType>Personal</nameType>
      <name>H. Abarca</name>
    </creators>
    <creators>
      <nameType>Personal</nameType>
      <name>R. Deen</name>
    </creators>
    <titles>
      <title>InSight Cameras Bundle</title>
      <lang>en</lang>
    </titles>
    <publisher>NASA Planetary Data System</publisher>
    <publicationYear>2019</publicationYear>
    <contributors>
      <nameType>Organizational</nameType>
      <name>Planetary Data System: PDS Cartography and Imaging Sciences Discipline Node</name>
      <contributorType>DataCurator</contributorType>
    </contributors>
    <types>
      <resourceTypeGeneral>Collection</resourceTypeGeneral>
      <resourceType>PDS4 Bundle</resourceType>
    </types>
    <url>https://pds.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Ainsight_cameras&amp;version=1.0</url>
    <created>2020-05-07T22:12:05.000000Z</created>
    <updated>2020-05-07T22:12:05.000000Z</updated>
    <state>findable</state>
    <language>en</language>
    <schemaVersion>http://datacite.org/schema/kernel-4</schemaVersion>
  </attributes>
</data>`
The translated json gives:
```

{
  "doi": "10.17189/20151",
  "suffix": {
    "_text": 20151
  },
  "identifiers": [
    {
      "identifier": "20151",
      "identifierType": "IAD ID"
    },
    {
      "identifier": "urn:nasa:pds:insight_cameras::1.0",
      "identifierType": "Site ID"
    }
  ],
  "creators": [
    {
      "nameType": "Personal",
      "name": "J. Maki"
    },
    {
      "nameType": "Personal",
      "name": "P. Zamani"
    },
    {
      "nameType": "Personal",
      "name": "H. Abarca"
    },
    {
      "nameType": "Personal",
      "name": "R. Deen"
    }
  ],
  "titles": [
    {
      "title": "InSight Cameras Bundle",
      "lang": "en"
    }
  ],
  "publisher": "NASA Planetary Data System",
  "publicationYear": "2019",
  "contributors": [
    {
      "nameType": "Organizational",
      "name": "Planetary Data System: PDS Cartography and Imaging Sciences Discipline Node",
      "contributorType": "DataCurator"
    }
  ],
  "types": {
    "resourceTypeGeneral": "Collection",
    "resourceType": "PDS4 Bundle"
  },
  "url": "https://pds.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Ainsight_cameras&version=1.0",
  "created": "2020-05-07T22:12:05.000000Z",
  "updated": "2020-05-07T22:12:05.000000Z",
  "state": "findable",
  "language": "en",
  "schemaVersion": "http://datacite.org/schema/kernel-4"
}
```

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I added a generic version of the fix. It iterates through the record json and replaces any `_text` with its own value. I was able to test with your example and some of my own.

**Review by tloubrieu-jpl — APPROVED** [review]
Thanks you @eddiesarevalo that works and recursion is elegant !
